### ISSUE TITLE
cargo outdated on rust-analyzer failed on windows

### ISSUE THREAD

**Issue by kjeremy** [kbknapp/cargo-outdated#165] opened 2019-04-03 14:11 UTC
The `jemalloc-sys` crate isn't used on windows. I think this may be related to feature detection.

$ `cargo outdated`
> error: failed to select a version for `jemalloc-sys`.
>     ... required by package `jemalloc-ctl v0.2.0`
>     ... which is depended on by `ra_ide_api v0.1.0 (C:\Users\jkolb\AppData\Local\Temp\cargo-outdatedpl3WFC\crates\ra_ide_api)`
>     ... which is depended on by `ra_cli v0.1.0 (C:\Users\jkolb\AppData\Local\Temp\cargo-outdatedpl3WFC\crates\ra_cli)`
> versions that meet the requirements `^0.1.7` are: 0.1.8, 0.1.7
> 
> the package `jemalloc-sys` links to the native library `jemalloc`, but it conflicts with a previous package which links to `jemalloc` as well:
> package `jemalloc-sys v0.3.0`
>     ... which is depended on by `jemallocator v0.3.0`
>     ... which is depended on by `ra_ide_api v0.1.0 (C:\Users\jkolb\AppData\Local\Temp\cargo-outdatedpl3WFC\crates\ra_ide_api)`
>     ... which is depended on by `ra_cli v0.1.0 (C:\Users\jkolb\AppData\Local\Temp\cargo-outdatedpl3WFC\crates\ra_cli)`
> 
> failed to select a version for `jemalloc-sys` which could resolve this conflict

**Comment by kornelski** [comment] 2019-04-04 08:35
Thanks for the report. This is duplicate of #157

**Closed by kornelski** 2019-04-04 08:35 UTC
