### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by tjodden** [kbknapp/cargo-outdated#197] opened 2020-02-04 22:28 UTC
I get network errors when trying to run `cargo outdated` at work, where using a HTTPS proxy is required for all outgoing connections. It seems like `cargo outdated` does not respect the system proxy settings (i.e. `HTTPS_PROXY` environment variable). Since the regular `cargo update` command *does* work fine, it's probably just some setup for cargo-the-library missing in `cargo outdated`.

For reference, I get the following error when trying to use `cargo outdated` at work:

```
$ cargo outdated -v
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
 Updating... compat workspace
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
error: failed to load source for a dependency on `clap`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to connect to github.com: Connection timed out; class=Os (2)
```

**Comment by deg4uss3r** [comment] 2020-02-05 14:26
Hi @tjodden can you let me know which version of `cargo outdated` you are using? 

Thanks!!

**Comment by tjodden** [comment] 2020-02-05 14:39
Version 0.9.1.

**Comment by deg4uss3r** [comment] 2020-02-05 15:00
Thanks @tjodden we believe we solved this with #192 could you update by doing the following and see if it works with your company proxy? 

`cargo install --git https://github.com/kbknapp/cargo-outdated` 

You should see `v0.9.4` after updating to the master branch.

**Comment by tjodden** [comment] 2020-02-05 16:29
Unfortunately the problem remains after updating:

```
$ cargo outdated --version
cargo-outdated v0.9.4
$ cargo outdated -v
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
 Updating... compat workspace
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
error: failed to load source for a dependency on `clap`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to connect to github.com: Connection timed out; class=Os (2)
```

I verified that `cargo update` still works:

```
$ cargo update
    Updating crates.io index
    Updating arrayref v0.3.5 -> v0.3.6
      Adding autocfg v1.0.0
    Updating backtrace v0.3.40 -> v0.3.43
      Adding base64 v0.11.0
    Updating blake2b_simd v0.5.9 -> v0.5.10
```

**Comment by deg4uss3r** [comment] 2020-02-05 18:58
Thanks @tjodden Could you expand a bit more on how you setup your proxy (you don't have to divulge any corporate links, I'm just curious what could be different than below)? I tested this on both MacOS and Ubuntu (19.04).

For example, I'm trying to reproduce the error I am using `[pproxy](https://github.com/qwj/python-proxy)` as it's the most up-to-date http(**s**) proxy I could find that was quick to setup and see the results.

I ran with `pproxy -v` and watched it's output in a terminal instance. 

Then, I used all of the following environmental variables: 

```
https_proxy=127.0.0.1:8080
http_proxy=127.0.01:8080
HTTPS_PROXY=localhost:8080
HTTP_PROXY=localhost:8080
```

When running `cargo outdated`(`v0.9.4`) I am seeing it hit the github api with: 
```
> pproxy -v
Serving on :8080 by http,socks4,socks5
http 127.0.0.1:61051 -> api.github.com:443
http 127.0.0.1:61054 -> api.github.com:443
```

..and it checks the dependencies fine! 

Any info you could give me would be great to help debugging what the real issue is!

**Comment by tjodden** [comment] 2020-02-06 10:27
My setup is:

```
export HTTP_PROXY=http://proxy.corp:123
export HTTPS_PROXY=http://proxy.corp:234
export http_proxy=$HTTP_PROXY
export https_proxy=$HTTPS_PROXY
export NO_PROXY=.corp,localhost,127.0.0.1
```
Then, there is a firewall that disallows all outgoing connections from the corporate network, so you have to use the proxy server. To mimic this setup, I think you'd have to run pproxy on a different machine, and configure a firewall on your machine that blocks outgoing connections on port 443.

**Comment by tjodden** [comment] 2020-02-06 10:41
I ran `cargo outdated` through `strace` and it seems that the proxy *is* used *at first*, but a *later* connection attempt does not use it. This would explain why you saw hits in your proxy, even though it fails for me.

First  `connect`:

```
connect(4, {sa_family=AF_INET, sin_port=htons(912), sin_addr=inet_addr("{PROXY_IP}")}, 16) = -1 EINPROGRESS (Operation now in progress)
sendto(4, "CONNECT api.github.com:443 HTTP/"..., 114, MSG_NOSIGNAL, NULL, 0) = 114
```
Second `connect`:

```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 5
connect(5, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("140.82.118.3")}, 16) = -1 ETIMEDOUT (Connection timed out)
close(5)
```

**Comment by tjodden** [comment] 2020-02-06 11:11
I had a look at the `cargo` source, and found the following function in [src/bin/cargo/main.rs](https://github.com/rust-lang/cargo/blob/bb3f2c59274dbf181f2d1a58c54486df4292ec2a/src/bin/cargo/main.rs#L181):

```rust
fn init_git_transports(config: &Config) {
    // Only use a custom transport if any HTTP options are specified,
    // such as proxies or custom certificate authorities. The custom
    // transport, however, is not as well battle-tested.
```

I couldn't find any similar code in `cargo outdated`, so I copied this function as-is and added a call to it just after `Config` is created in `main`. And that solved the problem!

**Comment by deg4uss3r** [comment] 2020-02-06 13:55
Magic! That's great @tjodden 

Just to confirm (since I cannot replicate with my environment) you solved it like this: 
https://github.com/deg4uss3r/cargo-outdated/blob/proxy_resolve/src/main.rs#L114-L132

If you'd like to put in your solution as a PR that's great, if not I'll PR that change and merge it today. 

I test both on an off proxy and this works for me as well.

**Comment by tjodden** [comment] 2020-02-06 14:48
I tried your branch @deg4uss3r and it works excellent for me as well. Feel free to PR it.

However, running `cargo outdated` on it's own project in that branch gives the following error:

```
$ ./target/debug/cargo-outdated outdated      
error: failed to select a version for `libgit2-sys`.
    ... required by package `cargo v0.42.0`
    ... which is depended on by `cargo-outdated v0.9.6 (/tmp/cargo-outdatedNmuRY7)`
versions that meet the requirements `^0.9.0` are: 0.9.2, 0.9.1, 0.9.0

the package `libgit2-sys` links to the native library `git2`, but it conflicts with a previous package which links to `git2` as well:
package `libgit2-sys v0.10.0`
    ... which is depended on by `git2 v0.11.0`
    ... which is depended on by `git2-curl v0.12.0`
    ... which is depended on by `cargo-outdated v0.9.6 (/tmp/cargo-outdatedNmuRY7)`

failed to select a version for `libgit2-sys` which could resolve this conflict
```

No problem running `cargo build` though, so I'm not sure what's going on.

**Comment by deg4uss3r** [comment] 2020-02-06 14:55
It's trying to build with a newer `git2-curl` which is using a newer`libgit2-sys` than `cargo` uses, and that's a system-level conflict... I ran into that while testing this build, you *have* to use `git2-curl:0.11` which is `libgit2-sys:0.9`.

**Comment by deg4uss3r** [comment] 2020-02-06 16:52
Merged :)

**Closed by deg4uss3r** 2020-02-06 16:52 UTC

**Comment by tjodden** [comment] 2020-02-06 21:55
Thanks!
