### ISSUE TITLE
Yanked package causes "Cannot find matched versions of package"

### ISSUE THREAD

**Issue by Julusian** [kbknapp/cargo-outdated#168] opened 2019-05-11 03:08 UTC
I have a project depending on bitflags@1.0.5, which has been yanked.
This is causing `cargo outdated` to panic:
```
thread 'main' panicked at 'Cannot find matched versions of package bitflags from source registry `https://github.com/rust-lang/crates.io-index`', /home/julus/.cargo/git/checkouts/cargo-outdated-cb22c4b2a8aff03f/ce4b6ba/src/cargo_ops/temp_project.rs:312:32
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   5: cargo_outdated::cargo_ops::temp_project::TempProject::find_update::{{closure}}
   6: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   7: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
   8: cargo_outdated::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: _start

```

Version: ce4b6bad (Latest master)

**Comment by deg4uss3r** [comment] 2019-10-14 15:00
Hi @Julusian I was trying to reproduce the issue this morning but failed to do so with cargo `v1.37.0 (9edd08916 2019-08-02)`. What I get now is: 

```
> cargo outdated
  Parsing... current workspace
Resolving... current workspace
error: failed to select a version for the requirement `bitflags = "= 1.0.5"`
  candidate versions found which didn't match: 1.2.1, 1.2.0, 1.1.0, ...
  location searched: crates.io index
required by package `yanked_package v0.1.0 (~/code/rust_experiments/yanked_package)`
```

Are you still able to make `cargo-outdated` panic by using a yanked crate?

**Comment by jonhoo** [comment] 2019-11-07 15:44
I get the same issue on the `async-await` branch of https://github.com/mit-pdos/noria (comment out the `patch` section in the root `Cargo.toml`), though there no crates are yanked as far as I'm aware. This is with
```console
$ cargo version
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
```

**Comment by deg4uss3r** [comment] 2019-11-07 16:49
Thanks @jonhoo I can see a panic now, looks like roughly the same issue above:

```
degausser on mac-laptop in ~/code/noria
[mit-pdos/noria.git:async-await]> cargo outdated
  Parsing... current workspace
Resolving... current workspace
thread 'main' panicked at 'Cannot find matched versions of package tokio-tower from source registry `https://github.com/rust-lang/crates.io-index`', src/cargo_ops/temp_project.rs:316:17
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::continue_panic_fmt
   3: std::panicking::begin_panic_fmt
   4: cargo_outdated::cargo_ops::temp_project::TempProject::find_update::{{closure}}
   5: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   6: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
   7: cargo_outdated::main
   8: std::rt::lang_start::{{closure}}
   9: main
```

There appears to be something fishy with how it is resolving a `tokio-tower` dependency. I'm looking into the root cause now.

**Comment by deg4uss3r** [comment] 2019-11-07 18:42
Okay, after many print statement debugging attempts I see the issue is here[0]. I *think* this complicated block could be replaced with `semver::Version.parse(requirement) == version` for better semantic version matching. :)

**Comment by deg4uss3r** [comment] 2019-12-05 18:31
@jonhoo Can you try with the latest merge (`v0.9.1`)? Thanks!

**Comment by jonhoo** [comment] 2019-12-10 17:45
@deg4uss3r hmm, I now get:
```
thread 'main' panicked at 'Error could not parse requirement into a semantic version: ParseError("Error parsing major identifier")', src/libcore/result.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:82
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1187
  15: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
  16: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
  17: cargo_outdated::execute
  18: cargo_outdated::main
  19: std::rt::lang_start::{{closure}}
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
When running `cargo outdated` from the root on the `master` branch of the same repository?

**Comment by deg4uss3r** [comment] 2019-12-11 00:30
Ah I see the `=` within the quotes is messing with it, looking into it

**Comment by deg4uss3r** [comment] 2019-12-11 22:33
@jonhoo Can you catch the latest branch after the merge? I believe the error we see now on master should be there. Please let me know if I am wrong.

**Comment by jonhoo** [comment] 2019-12-11 22:44
I'm not sure I understand what you mean by "catch the latest branch after the merge"?

**Comment by deg4uss3r** [comment] 2019-12-12 18:00
I’m sorry that was auto correct, can you pull the latest commit from master and try that.

**Comment by jonhoo** [comment] 2019-12-12 18:10
That seems to have done it! :tada:

**Comment by deg4uss3r** [comment] 2019-12-18 15:09
I'll go ahead and close this issue now `v0.9.2` has resolved this.

**Closed by deg4uss3r** 2019-12-18 15:09 UTC
