### ISSUE TITLE
Latest release doesn't work with --locked

### ISSUE THREAD

**Issue by kpcyrd** [kbknapp/cargo-outdated#177] opened 2019-11-23 23:51 UTC
Hello!

just letting you know that the latest release tarball ships an outdated Cargo.lock which breaks `cargo build --release --locked`

**Comment by est31** [comment] 2019-12-04 15:07
:+1: dear maintainers could you please publish a crates.io release?

**Comment by est31** [comment] 2019-12-04 15:46
ping @Frederick888 @kbknapp

**Comment by Frederick888** [comment] 2019-12-05 04:56
Ah, sorry, I feel guilty for this one, been kinda busy for quite a while now. I've just published v0.9.0 to crates.io.

And ping @kbknapp, is it ok for me to add @kornelski as a co-owner of this crate? I'd wait until Sunday in case you've got any concerns.

**Comment by est31** [comment] 2019-12-05 04:58
Thanks @Frederick888 for the quick release!

**Comment by est31** [comment] 2019-12-06 01:42
@Frederick888 sorry to bother you again but what exactly did the 0.9.0 release include?

I had hoped you'd publish latest master but apparently 0.9.0 still depends on cargo 0.38. The issue is that I have switched some of my projects to the Cargo.lock 2.0 format. However, support for that has only landed in 0.40 (or maybe 0.39, not sure) so I'd really love a release which includes the update to that (latest master has such an update). Thanks!

**Comment by Frederick888** [comment] 2019-12-06 02:24
@est31 I checked out the `v0.9.0` tag (which is the standard practice I reckon?). If you guys want the latest changes to land in crates.io I think a new tag is needed first.

**Comment by est31** [comment] 2019-12-06 02:53
Okay then can you maybe add a new tag to latest master? `v0.9.1` or something? That would be great :).

**Comment by Frederick888** [comment] 2019-12-06 03:09
@kornelski @deg4uss3r Y'all ok for me to bump the version to 0.9.1? As I'm not actively maintaining this project right now so just to make sure I don't break your workflow.

**Comment by deg4uss3r** [comment] 2019-12-06 13:07
@Frederick888 Works for me!

**Comment by Frederick888** [comment] 2019-12-08 13:10
I've just publish 0.9.1 (68590f5) and invited @kornelski and @deg4uss3r to maintain the crate. Let me know if there are any other issues.

**Closed by Frederick888** 2019-12-08 13:10 UTC
