### ISSUE TITLE
error: failed to select a version for `protobuf`

### ISSUE THREAD

**Issue by cberner** [kbknapp/cargo-outdated#232] opened 2020-07-27 04:17 UTC
cargo-outdated fails on the fleetfs crate.

Steps to reproduce:
```
git clone https://github.com/fleetfs/fleetfs
cd fleetfs
cargo outdated
```

Expected: shows the outdated dependencies

Actual:
```
error: failed to select a version for `protobuf`.
    ... required by package `raft v0.5.0`
    ... which is depended on by `fleetfs v0.2.0 (/tmp/cargo-outdated0C2uPW)`
versions that meet the requirements `~2.0-2.2` are: 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0

all possible versions conflict with previously selected packages.

  previously selected package `protobuf v2.16.2`
    ... which is depended on by `fleetfs v0.2.0 (/tmp/cargo-outdated0C2uPW)`

failed to select a version for `protobuf` which could resolve this conflict
```

**Comment by deg4uss3r** [comment] 2020-08-20 23:39
Hi! this is a well known error that isn't a `cargo` bug but more of a feature! 

See this [comment](https://github.com/kbknapp/cargo-outdated/issues/230#issuecomment-661333240) for a more detailed description. Basically it boils down to how we compute the workspace after trying to update a crate. 

This is a duplicate of #230

**Closed by deg4uss3r** 2020-08-20 23:39 UTC
